config:
  logger:
    level: debug
    filename: qlinker.log
  watchdog:
    enable: true
  global:
    mute: ['1080P']
    exclude: ['.zip', '.rar', '.7z']
    format: '{name} - S{season}E{episode} - {meta}'
tasks:
  mushoku:
    src: D:\Videos\Downloads\Mushoku Tensei\Season 02
    dest: D:\Videos\Bangumi\Mushoku Tensei\Season 02
    rename:
      enable: true
      name: Mushoku Tensei
      season: 2
      meta: '[Sakurato][AVC-8bit 1080P AAC][CHS]'
      mute: ['8bit']